### ISSUE TITLE
Display query stats to the right of the results again

### ISSUE THREAD

**Issue by daledude** [smi2/tabix.ui#10]
I liked the way the old version had put the queries performance stats at the right of the results tab. I know there is a Stats tab now, which is useful (and not always being updated), but the stats being displayed immediately with the results was very convenient :)

![clickhouse-tabix](https://cloud.githubusercontent.com/assets/590325/24886800/2b808dc2-1e25-11e7-9b95-a8993efaf3e6.PNG)

**Comment by isublimity** [comment]
try new release
