### ISSUE TITLE
SQL results table header vs bottom horisontal scrollbar

### ISSUE THREAD

**Issue by k-pozdeev** [smi2/tabix.ui#11]
Tabix.io Build 17.03.1 [20170323]
Chromium Browser Version 56.0.2924.76 Built on Ubuntu , running on LinuxMint 18.1 (64-bit)

After I run SQL query and make a look at result in a table below, I meet some inconvenience. Is it possible to keep both table header and bottom horizontal scrollbar on a results area? Situation is illustrated by two screenshots in attachment. Thanks!

![1](https://cloud.githubusercontent.com/assets/8384200/24909863/6a20269c-1ece-11e7-9c3c-967095fcdae9.png)
![2](https://cloud.githubusercontent.com/assets/8384200/24909862/6a202eda-1ece-11e7-88b9-393060b4bfdb.png)

**Comment by isublimity** [comment]
try new release

**Comment by k-pozdeev** [comment]
Works fine, thanks!
