### ISSUE TITLE
Tabix does not connect to host with path (http://host:80/admin/clickhouse_proxy/)

### ISSUE THREAD

**Issue by rasl** [smi2/tabix.ui#14]
Does not connect to host with path (http://host:80/admin/clickhouse_proxy/)
The root cause of bug: connection url is converted to http://host:80/admin/clickhouse_proxy/:8123 (added 8123 as default port)
https://github.com/smi2/tabix.ui/blob/master/src/app/services/api.js#L42

**Comment by isublimity** [comment]
fix
