### ISSUE TITLE
Make add_http_cors_header and log_queries optional

### ISSUE THREAD

**Issue by bolsunovskyi** [smi2/tabix.ui#18]
Hi, when using readonly in tabix it's impossible to login 
> Code: 164, e.displayText() = DB::Exception: Cannot override setting (add_http_cors_header) in readonly mode, e.what() = DB::Exception

But when I manually remove this flags from code all works good. That is why I have such proposition.
As for CORS headers, it could be simply added on nginx.

**Comment by isublimity** [comment]
Tabix Requirements: not readonly user or `setting readonly=2`

https://tabix.io/doc/Requirements/#note
