### ISSUE TITLE
Нормальные хоткеи. 

### ISSUE THREAD

**Issue by AlexAkulov** [smi2/tabix.ui#19]
Всё круто, но я уже полчаса не могу разобраться как мне выполнить `SELECT 1;`
```
Hot keys
⌘ + Enter

Exec current query
⌘ + Shift + Enter

Exec all query
⌘ + Y

Drop current line
⌘ + ⇧ + F

Reformat
⌘ + ⇧ + Plus|Minus

свернуть все/развернуть
```
Что это такое `⌘` ?! У менять нет такой кнопки на клавиатуре. 
Перепробовал все возможные сочетания Shift, Ctrl, Alt +Enter. Ничего не работат! 
Может `SELECT 1` это вообще что-то не валидное, я не знаю, или это только на Маке работает?

**Comment by isublimity** [comment]
Попробуйте Ctrl+Enter - получится ?

**Comment by AlexAkulov** [comment]
Проблема оказалась в Firefox 53.0.2 (32-бит)

https://gyazo.com/88f9bca1a41dcd5faa28c2216a5cc7bd

**Comment by isublimity** [comment]
поправлено

**Comment by AlexAkulov** [comment]
В Мозилле теперь работает, спасибо!
Но в хелпе всё-равно уродские Маковские клавиши остались.
