### ISSUE TITLE
XSS again

### ISSUE THREAD

**Issue by vas-and-tor** [smi2/tabix.ui#2]
Hi.
Please look at the result of this code in tabix:
```
select "<script>alert('Hi, its me again!');</script>"
```

Quotes are incorrect, I know.

**Comment by isublimity** [comment]
Ok) Thx

**Comment by isublimity** [comment]
It`s not XSS from data result,   
try this, fetch result from CH 
```
select '<script>alert("Hi, its me again!");</script>'
```

Alert show - from Error message -> fix

**Comment by vas-and-tor** [comment]
`select '<script>alert("Hi, its me again!");</script>' -- It works!` :smile: 

But without comment it doesn't.

**Comment by isublimity** [comment]
ThX! fix and this )
