### ISSUE TITLE
Direct connection by IP address or host name faild

### ISSUE THREAD

**Issue by daskol** [smi2/tabix.ui#24]
I deployed tabix on my own host. Then I tried to estabilish direct connect to CH by IP address as it is depicted bellow. I got error message but still it is possible to connect to local forwarded port 8123.

CH is avaliable via HTTP since command like
```bash
    curl 12.34.56.789:8123
```
returns `Ok.`

![image](https://cloud.githubusercontent.com/assets/9336514/26660494/21126caa-4681-11e7-872c-fadbe619f0e4.png)

**Comment by isublimity** [comment]
login try "default"

**Comment by daskol** [comment]
No, I still get `Ошибка доступа`. By the way there is not records about that fail in access or error logs of nginx before clickhouse.

**Comment by isublimity** [comment]
Fix translate in last release , and fix api
