### ISSUE TITLE
Results on the right are cut off by scroll bar

### ISSUE THREAD

**Issue by daledude** [smi2/tabix.ui#25]
In the results table the last column is cut off by a scroll bar. When in full screen this doesn't happen.

![clickhouse-overflow](https://cloud.githubusercontent.com/assets/590325/26763651/44685728-4924-11e7-8c76-e770f02d42e0.PNG)

**Comment by isublimity** [comment]
i try fix last build

**Comment by isublimity** [comment]
Fix in master
