### ISSUE TITLE
Не открывается таб DRAW в Chromium. 

### ISSUE THREAD

**Issue by TvoroG** [smi2/tabix.ui#28]
Привет! Спасибо за tabix.

Проблема в следующем: выполняю запрос, получаю ответ, пытаюсь открыть таб draw и в этот момент все виснит и через пару секунд страница падает с ошибкой "Aw, Snap! Something went wrong while displaying this webpage".

Chromium Version 57.0.2987.133 (64-bit)
Tabix.io Build 17.06.1 [20170614]

Если еще какая-то информация нужна, могу скинуть.

**Comment by TvoroG** [comment]
Если добавить в запрос DRAW_CHART {}, то все равно падает

**Comment by TvoroG** [comment]
И еще почему-то при выполнении запроса сильно нагружается процессор. Это не только к этому случаю относится

**Comment by TvoroG** [comment]
Если удалить md-progress-linear, нагрузка пропадает

**Comment by isublimity** [comment]
А что в консоле разработчика ? Есть JS ошибки ?

**Comment by TvoroG** [comment]
```
Execute query
app-9fdb8cae18.js:25 Un support DrawType:null
isExecutableCode() false
Can't get dom width or height
widget.draw.preProcessor
app-9fdb8cae18.js:25 DrawEchartsChart
```

**Comment by isublimity** [comment]
Спасибо, буду пробовать эмулировать поведение -> фиксить

**Comment by TvoroG** [comment]
Такая же беда и в Chromium Version 59.0.3071.109 (Developer Build) (64-bit)

**Comment by isublimity** [comment]
Попробуйте Версия 61.0.3153.0 (Сборка для разработчиков), (64 бит)

Будет тоже самое ? Поставил эту - на macOS не воспроизвелось 
И в какой OS

**Comment by TvoroG** [comment]
Изначально пробовал на линуксе. 61 версию испытал на винде и все равно виснет.

**Comment by isublimity** [comment]
Поставил под Win версию 61 - все ок 

Может он из за данных вешается 

Попробуйте сделать 

```

select 1 


```

И переключиться на вкладку draw

**Comment by isublimity** [comment]
Так-же проверил в YandexBrowser под Mac - тоже ок

**Comment by TvoroG** [comment]
`select 1` сработал

**Comment by isublimity** [comment]
Попробуйте найти вариант когда крашиться, может меньше строк нужно достать
Я тестировал графики на небольших обьемах данных ...

**Comment by TvoroG** [comment]
Привет! Нашел все таки проблему.
У меня в запросе возвращаются две колонки: x и y. В колонке x находится unix timestamp, т.е. большое целое число. В https://github.com/smi2/tabix.ui/blob/faa82cda0e8e408157cd2e019a4819a94c496e8b/src/app/draw/draw-echarts-chart.js#L176 создается массив, где индексами являются числа из x. Тут создается массив из конструктора Array, т.е. не создается полный массив. А вот здесь уже он пытается создать полный и падает: https://github.com/smi2/tabix.ui/blob/faa82cda0e8e408157cd2e019a4819a94c496e8b/src/app/draw/draw-echarts-chart.js#L203

**Comment by isublimity** [comment]
Попробуйте новый build

**Comment by TvoroG** [comment]
Все работает, спасибо!
