### ISSUE TITLE
Ошибка ERR_RESPONSE_HEADERS_TOO_BIG

### ISSUE THREAD

**Issue by kirill3000** [smi2/tabix.ui#31]
Выполняю запрос в консоле select count(distinct (ID)) from T - возвращает 1 запись
Выполняю запрос через tabix 
Failed to load resource: net::ERR_RESPONSE_HEADERS_TOO_BIG

**Comment by daledude** [comment]
Changing either (or both) of these fixes the issue:
```
send_progress_in_http_headers=1
http_headers_progress_interval_ms=1
```
These files contain those options:
```
./src/app/services/api.js
./build/scripts/app-9d3cae64a4.js
./build/scripts/app.js
./build/scripts/app-2dfa2abab9.js
```

**Comment by isublimity** [comment]
fix in buld in 2017-08-10

**Comment by isublimity** [comment]
release fix
