### ISSUE TITLE
Некорректное отображение больших цифр (на примере UInt64)

### ISSUE THREAD

**Issue by vmugue** [smi2/tabix.ui#42]
![image](https://user-images.githubusercontent.com/7193170/31608688-d769d862-b279-11e7-943c-4b607f82ed6d.png)

В примере запрос: 
select toString(visit_id), visit_id
from visits 
where visit_id = 18017313154537368237

Судя по toString(visit_id) - фильтрация проходит корректно, но отображение visit_id не верное.

**Comment by isublimity** [comment]
Проблемный SQL
```sql
SELECT number+18017313154537368000,sin(number),cos(number) FROM system.numbers LIMIT 400
```

Поправлено в Beta : beta.tabix.io 
Fix : `output_format_json_quote_64bit_integers=1`

commits : 
https://github.com/smi2/tabix.ui/commit/eab31a528289131e09268b3d62cb4f904436bb95
https://github.com/smi2/tabix.ui/commit/26f21e44f37aba95a8ab0fca94203078a713c3fe#diff-ba9caf9daa3271c1c9093550ccf7bdc8R275

**Comment by isublimity** [comment]
Fix in master
