### ISSUE TITLE
CH without auth

### ISSUE THREAD

**Issue by Foxsa** [smi2/tabix.ui#45]
With new tabix.io I can not connect to my clickhouse which configured without authorization. What can I do?

**Comment by isublimity** [comment]
Use username: default

**Comment by Foxsa** [comment]
Now I`ve got an error:
Code: 115, e.displayText() = DB::Exception: Unknown setting output_format_json_quote_denormals, e.what() = DB::Exception
Old tabix still works ok

**Comment by isublimity** [comment]
use settings old CH version on login

**Comment by isublimity** [comment]
Server < 1.1.54276

**Comment by Foxsa** [comment]
Thanks!
