### ISSUE TITLE
Выгрузка в csv

### ISSUE THREAD

**Issue by SerdyukovA** [smi2/tabix.ui#6]
Никак не могу найти кнопку выгрузки результата запроса в csv. Подскажите)
Спасибо!

**Comment by isublimity** [comment]
Только в планах перенести эту ф-цию из старой версии

**Comment by SerdyukovA** [comment]
Есть ориентировочные сроки какие-то? Мы тогда вернемся к старой версии, так как самый нужный на текущий момент функционал для большого числа людей...
Спасибо!

**Comment by isublimity** [comment]
Посмотрю на этой недели - раз есть необходимость

**Comment by isublimity** [comment]
https://twitter.com/tabix_io/status/849871607984205824

done)
