### ISSUE TITLE
Parse problem with simple query

### ISSUE THREAD

**Issue by pilat** [smi2/tabix.ui#7]
Hello! 
I'm run follow queries on fresh ClickHouse server with using http://ui.tabix.io/sql:
`CREATE DATABASE pc1;`
`CREATE TABLE t (a UInt8) ENGINE = Memory;`
These commands are executed successfully.

Then, I execute the following query:
`INSERT INTO t values (1), (2), (3);`
And get the exception:
> 2017.04.07 18:58:45.112701 [ 10 ] <Error> executeQuery: Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected ( before: /*TABIX_QUERY_ID_ec0JCHn37U409iQ_()*/: (at row 4)
, e.what() = DB::Exception (from 188.11.12.13:52766) (in query: INSERT INTO pc1.t values ),

This command, executed with clickhouse-client Is successful

I'm using
Server version 1.1.54198. 
Chrome Version 57.0.2987.133 (64-bit) OSX

**Comment by isublimity** [comment]
https://github.com/smi2/tabix.ui/commit/7f77093305ae1177287780e048418c21361927b9

**Comment by isublimity** [comment]
https://github.com/smi2/tabix.ui/commit/037060d52cd1b4a34460ddbfa8a1fcccd3496f35

**Comment by isublimity** [comment]
Thx for report bug!

```
DROP TABLE IF EXISTS t
;;
CREATE TABLE t (a UInt8) ENGINE = Memory;
;;
INSERT INTO t values (1), (2), (3);
;;
SELECT * FROM t
```
Done)
