### ISSUE TITLE
Very laggy

### ISSUE THREAD

**Issue by daledude** [smi2/tabix.ui#8]
I'm sorry I don't know what else to provide other than the below. I used the original app a few months ago at http://guiclickhouse.smi2.ru and it was responsive. The new app at http://guiclickhouse.smi2.ru and this tabix.ui seem very laggy now. I have a number of tabs open with other SPA's and this app usually takes 20-50% cpu.

Intel i7
Windows 10
Chrome 57.0.2987.133

**Comment by isublimity** [comment]
Yes unfortunately this is a big problem Tabix ;( 

This task/bug I have in high priority, now the solution is only to press F5 when starting to brake/slow the interface

**Comment by daledude** [comment]
I'll close this in favor of #12. The latest version has done very well tho. I've had the tab open for days and haven't had to refresh it yet. I appreciate the work!
